name: 'chnls_ui'
version: 0.0.1
description: channels ui
author: Hivepoint, Inc.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.16.0 <0.17.0'
  core_elements: ">=0.6.1+2 <0.7.0"
  paper_elements: '>=0.6.2+3 <0.7.0'
  chnls_core:
    path: ../chnls_core
transformers:
- polymer:
    entry_points: web/index.html
    csp: true
- $dart2js:
    csp: true