name: chnls_core
description: channels core package
author: Hivepoint, Inc.
version: 0.0.1
dev_dependencies:
  unittest: any
dependencies:
  crypto: any
  exportable: any
  googleapis_auth: any
  googleapis: any
  uuid: any
  email:
    path: ../email
  